In [4]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [6]:
from dotenv import load_dotenv
load_dotenv()

True

In [7]:
import pandas as pd
books = pd.read_csv("book_cleaned.csv")

In [8]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_description,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [9]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [10]:
books["tagged_description"].to_csv("tagged_description.txt", index=False, header=False)

In [11]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=0, separator="\n")
documents= text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 500
Created a chunk of size 1216, which is longer than the specified 500
Created a chunk of size 962, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 881, which is longer than the specified 500
Created a chunk of size 1090, which is longer than the specified 500
Created a chunk of size 1191, which is longer than the specified 500
Created a chunk of size 515, which is longer than the specified 500
Created a chunk of size 754, which is longer than the specified 500
Created a chunk of size 730, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 1267, which is longer than the specified 500
Created a chunk of size 683, which is longer than the specified 500
Created a chunk of size 555, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 789, which is longer than the specified 500
Created a chunk of size 566, which is longer than the specified 500
Created a chunk of size 525, which is longer than the specified 500
Created a chunk of size 535, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 565, which is longer than the specified 500
Created a chunk of size 597, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 889, which is longer than the specified 500
Created a chunk of size 695, which is longer than the specified 500
Created a chunk of size 2010, which is longer than the specified 500
Created a chunk of size 522, which is longer than the specified 500
Created a chunk of size 649, which is longer than the specified 500
Created a chunk of size 778, which is longer than the specified 500
Created a chunk of size 688, which is longer than the specified 500
Created a chunk of size 550, which is longer than the specified 500
Created a chunk of size 1225, which is longer than the specified 500
Created a chunk of size 1186, which is longer than the specified 500
Created a chunk of size 1216, which is longer than the specified 500
Created a chunk of size 1193, which is longer than the specified 500
Created a chunk of size 1059, which is longer than the specified 500
Created a chunk of size 690, which is longer than the specified 500
Created a chunk of size 878, which is longer than the specified 500
Created a chunk of size 768, which is longer than the specified 500
Created a chunk of size 725, which is longer than the specified 500
Created a chunk of size 528, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 901, which is longer than the specified 500
Created a chunk of size 1272, which is longer than the specified 500
Created a chunk of size 560, which is longer than the specified 500
Created a chunk of size 1637, which is longer than the specified 500
Created a chunk of size 779, which is longer than the specified 500
Created a chunk of size 718, which is longer than the specified 500
Created a chunk of size 516, which is longer than the specified 500
Created a chunk of size 960, which is longer than the specified 500
Created a chunk of size 1132, which is longer than the specified 500
Created a chunk of size 1325, which is longer than the specified 500
Created a chunk of size 853, which is longer than the specified 500
Created a chunk of size 801, which is longer than the specified 500
Created a chunk of size 1121, which is longer than the specified 500
Created a chunk of size 838, which is longer than the specified 500
Created a chunk of size 734, which is longer than the specified 500
Created a chunk of size 1195, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 775, which is longer than the specified 500
Created a chunk of size 768, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 718, which is longer than the specified 500
Created a chunk of size 2012, which is longer than the specified 500
Created a chunk of size 1288, which is longer than the specified 500
Created a chunk of size 1231, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 750, which is longer than the specified 500
Created a chunk of size 1242, which is longer than the specified 500
Created a chunk of size 914, which is longer than the specified 500
Created a chunk of size 846, which is longer than the specified 500
Created a chunk of size 1128, which is longer than the specified 500
Created a chunk of size 1075, which is longer than the specified 500
Created a chunk of size 1320, which is longer than the specified 500
Created a chunk of size 2834, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500
Created a chunk of size 1006, which is longer than the specified 500
Created a chunk of size 715, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 2510, which is longer than the specified 500
Created a chunk of size 956, which is longer than the specified 500
Created a chunk of size 641, which is longer than the specified 500
Created a chunk of size 525, which is longer than the specified 500
Created a chunk of size 795, which is longer than the specified 500
Created a chunk of size 1424, which is longer than the specified 500
Created a chunk of size 1085, which is longer than the specified 500
Created a chunk of size 1146, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 790, which is longer than the specified 500
Created a chunk of size 1088, which is longer than the specified 500
Created a chunk of size 874, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 808, which is longer than the specified 500
Created a chunk of size 1814, which is longer than the specified 500
Created a chunk of size 1830, which is longer than the specified 500
Created a chunk of size 1064, which is longer than the specified 500
Created a chunk of size 955, which is longer than the specified 500
Created a chunk of size 1182, which is longer than the specified 500
Created a chunk of size 1286, which is longer than the specified 500
Created a chunk of size 1644, which is longer than the specified 500
Created a chunk of size 759, which is longer than the specified 500
Created a chunk of size 1932, which is longer than the specified 500
Created a chunk of size 874, which is longer than the specified 500
Created a chunk of size 2008, which is longer than the specified 500
Created a chunk of size 2285, which is longer than the specified 500
Created a chunk of size 1003, which is longer than the specified 500
Created a chunk of size 579, which is longer than the specified 500
Created a chunk of size 1144, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500
Created a chunk of size 1088, which is longer than the specified 500
Created a chunk of size 1483, which is longer than the specified 500
Created a chunk of size 1137, which is longer than the specified 500
Created a chunk of size 724, which is longer than the specified 500
Created a chunk of size 668, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 608, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 967, which is longer than the specified 500
Created a chunk of size 859, which is longer than the specified 500
Created a chunk of size 1034, which is longer than the specified 500
Created a chunk of size 652, which is longer than the specified 500
Created a chunk of size 735, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 1017, which is longer than the specified 500
Created a chunk of size 972, which is longer than the specified 500
Created a chunk of size 690, which is longer than the specified 500
Created a chunk of size 546, which is longer than the specified 500
Created a chunk of size 933, which is longer than the specified 500
Created a chunk of size 564, which is longer than the specified 500
Created a chunk of size 856, which is longer than the specified 500
Created a chunk of size 717, which is longer than the specified 500
Created a chunk of size 749, which is longer than the specified 500
Created a chunk of size 714, which is longer than the specified 500
Created a chunk of size 1090, which is longer than the specified 500
Created a chunk of size 725, which is longer than the specified 500
Created a chunk of size 706, which is longer than the specified 500
Created a chunk of size 1914, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 561, which is longer than the specified 500
Created a chunk of size 558, which is longer than the specified 500
Created a chunk of size 626, which is longer than the specified 500
Created a chunk of size 2616, which is longer than the specified 500
Created a chunk of size 1580, which is longer than the specified 500
Created a chunk of size 996, which is longer than the specified 500
Created a chunk of size 849, which is longer than the specified 500
Created a chunk of size 1530, which is longer than the specified 500
Created a chunk of size 2032, which is longer than the specified 500
Created a chunk of size 1619, which is longer than the specified 500
Created a chunk of size 700, which is longer than the specified 500
Created a chunk of size 824, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 1191, which is longer than the specified 500
Created a chunk of size 510, which is longer than the specified 500
Created a chunk of size 665, which is longer than the specified 500
Created a chunk of size 1284, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 1277, which is longer than the specified 500
Created a chunk of size 1058, which is longer than the specified 500
Created a chunk of size 784, which is longer than the specified 500
Created a chunk of size 971, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 759, which is longer than the specified 500
Created a chunk of size 965, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 788, which is longer than the specified 500
Created a chunk of size 650, which is longer than the specified 500
Created a chunk of size 986, which is longer than the specified 500
Created a chunk of size 799, which is longer than the specified 500
Created a chunk of size 1163, which is longer than the specified 500
Created a chunk of size 1058, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 819, which is longer than the specified 500
Created a chunk of size 757, which is longer than the specified 500
Created a chunk of size 571, which is longer than the specified 500
Created a chunk of size 628, which is longer than the specified 500
Created a chunk of size 868, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 623, which is longer than the specified 500
Created a chunk of size 1084, which is longer than the specified 500
Created a chunk of size 2762, which is longer than the specified 500
Created a chunk of size 1035, which is longer than the specified 500
Created a chunk of size 760, which is longer than the specified 500
Created a chunk of size 775, which is longer than the specified 500
Created a chunk of size 636, which is longer than the specified 500
Created a chunk of size 1010, which is longer than the specified 500
Created a chunk of size 1066, which is longer than the specified 500
Created a chunk of size 797, which is longer than the specified 500
Created a chunk of size 701, which is longer than the specified 500
Created a chunk of size 1226, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 555, which is longer than the specified 500
Created a chunk of size 592, which is longer than the specified 500
Created a chunk of size 728, which is longer than the specified 500
Created a chunk of size 1807, which is longer than the specified 500
Created a chunk of size 1017, which is longer than the specified 500
Created a chunk of size 684, which is longer than the specified 500
Created a chunk of size 741, which is longer than the specified 500
Created a chunk of size 924, which is longer than the specified 500
Created a chunk of size 969, which is longer than the specified 500
Created a chunk of size 647, which is longer than the specified 500
Created a chunk of size 678, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 801, which is longer than the specified 500
Created a chunk of size 856, which is longer than the specified 500
Created a chunk of size 672, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 762, which is longer than the specified 500
Created a chunk of size 798, which is longer than the specified 500
Created a chunk of size 681, which is longer than the specified 500
Created a chunk of size 929, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 735, which is longer than the specified 500
Created a chunk of size 870, which is longer than the specified 500
Created a chunk of size 933, which is longer than the specified 500
Created a chunk of size 774, which is longer than the specified 500
Created a chunk of size 772, which is longer than the specified 500
Created a chunk of size 649, which is longer than the specified 500
Created a chunk of size 1771, which is longer than the specified 500
Created a chunk of size 536, which is longer than the specified 500
Created a chunk of size 826, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 971, which is longer than the specified 500
Created a chunk of size 556, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 878, which is longer than the specified 500
Created a chunk of size 672, which is longer than the specified 500
Created a chunk of size 709, which is longer than the specified 500
Created a chunk of size 656, which is longer than the specified 500
Created a chunk of size 1270, which is longer than the specified 500
Created a chunk of size 738, which is longer than the specified 500
Created a chunk of size 1019, which is longer than the specified 500
Created a chunk of size 779, which is longer than the specified 500
Created a chunk of size 684, which is longer than the specified 500
Created a chunk of size 600, which is longer than the specified 500
Created a chunk of size 665, which is longer than the specified 500
Created a chunk of size 597, which is longer than the specified 500
Created a chunk of size 857, which is longer than the specified 500
Created a chunk of size 597, which is longer than the specified 500
Created a chunk of size 539, which is longer than the specified 500
Created a chunk of size 567, which is longer than the specified 500
Created a chunk of size 707, which is longer than the specified 500
Created a chunk of size 850, which is longer than the specified 500
Created a chunk of size 544, which is longer than the specified 500
Created a chunk of size 1179, which is longer than the specified 500
Created a chunk of size 906, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 509, which is longer than the specified 500
Created a chunk of size 1717, which is longer than the specified 500
Created a chunk of size 847, which is longer than the specified 500
Created a chunk of size 1681, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 661, which is longer than the specified 500
Created a chunk of size 605, which is longer than the specified 500
Created a chunk of size 993, which is longer than the specified 500
Created a chunk of size 1130, which is longer than the specified 500
Created a chunk of size 2005, which is longer than the specified 500
Created a chunk of size 1173, which is longer than the specified 500
Created a chunk of size 2141, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 1322, which is longer than the specified 500
Created a chunk of size 528, which is longer than the specified 500
Created a chunk of size 1114, which is longer than the specified 500
Created a chunk of size 666, which is longer than the specified 500
Created a chunk of size 910, which is longer than the specified 500
Created a chunk of size 1318, which is longer than the specified 500
Created a chunk of size 693, which is longer than the specified 500
Created a chunk of size 952, which is longer than the specified 500
Created a chunk of size 1123, which is longer than the specified 500
Created a chunk of size 776, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 533, which is longer than the specified 500
Created a chunk of size 1020, which is longer than the specified 500
Created a chunk of size 727, which is longer than the specified 500
Created a chunk of size 612, which is longer than the specified 500
Created a chunk of size 631, which is longer than the specified 500
Created a chunk of size 1009, which is longer than the specified 500
Created a chunk of size 618, which is longer than the specified 500
Created a chunk of size 884, which is longer than the specified 500
Created a chunk of size 581, which is longer than the specified 500
Created a chunk of size 911, which is longer than the specified 500
Created a chunk of size 1059, which is longer than the specified 500
Created a chunk of size 632, which is longer than the specified 500
Created a chunk of size 1255, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 1100, which is longer than the specified 500
Created a chunk of size 909, which is longer than the specified 500
Created a chunk of size 623, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 1145, which is longer than the specified 500

In [12]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [51]:
from langchain_huggingface.embeddings import HuggingFaceEmbeddings

In [61]:
import os
import torch
print("Torch version:", torch.__version__)

Torch version: 2.11.0+cpu

In [1]:
import torch
from langchain_huggingface import HuggingFaceEmbeddings

hf_embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)

E:\Book Recommender\.venv\Lib\site-packages\langchain_core\_api\deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

E:\Book Recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DEll\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [13]:
db_books = Chroma.from_documents(
    documents,
    embedding= hf_embeddings
)

In [14]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k= 10)
docs

[Document(id='78a015dd-cc03-41ff-8c20-d801ae8559fd', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(id='76e342c7-b708-4b1e-9777-6373ebf3d8ec', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='808904d8-46c6-40d2-bf26-d62c1fda6618', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='a6552f92-50f2-4fc3-bec9-885f74ba013a', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='bba5112a-0d54-4ccc-a0f7-3113ac197aae', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='70a888f7-8782-4a6a-b60c-09a6d7aad9b6', metadata={'source': 'tagged_description.txt'}, page_content='"9780689860072 Menolly flees her home, because she is not permitted to make music there, and is taken by the Masterharper himself to Harpershall, where she learns that only her own self-doubt stands in her way."\n"9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton\'s seriously silly signature animals."'),
 Document(id='f7196ed1-ccdf-4d26-807d-f5f919fcec99', metadata={'source': 'tagged_description.txt'}, page_content='"9780915811236 An old man named Socrates shows Danny that the best way of dealing with a bully is the way of the peaceful warrior, through courage and love."\n"9780918273826 A wealthy Japanese man, a Brazilian healer, a couple who raise homing pigeons, a pilgrim, and an American businessman find their lives altered by their encounter with the rain forest"'),
 Document(id='4dd13b2f-4f9c-42e2-9945-25c2525a61e8', metadata={'source': 'tagged_description.txt'}, page_content='"9780786849734 The Little Einsteins, equipped with their camera, go on a journey through space, exploring each of the planets, landing on Mars, and looking at the Earth from their spaceship, with a slideviewer for young readers to view pictures of what they saw."\n9780786851157 Children will delight in hearing and imagining all the wonderful sleepytime images Mimi\'s mama recites while tucking Mimi in for a night filled with the sweetest of dreams.'),
 Document(id='6875fc98-dff6-4f65-b50d-b21ee7ffbdfc', metadata={'source': 'tagged_description.txt'}, page_content='"9780007151240 It should be the most natural thing in the world. But in Tony Parsons\' latest bestseller, three couples discover that Mother Nature can be one hell of a bitch."'),
 Document(id='8cbfdb13-926b-41da-9f8e-b0764aa89e96', metadata={'source': 'tagged_description.txt'}, page_content='"9780060959036 Barbara Kingsolver\'s fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel\'s intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."')]

In [19]:
isbn_int = int(docs[0].page_content.split()[0].strip().replace('"',''))
books[books["isbn13"] == isbn_int]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_description,title_and_subtitle,tagged_description
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,0,The Sense of Wonder,9780067575208 First published more than three ...

In [29]:
def retrieve_semantic_recommendations(query: str, top_k: int = 50) -> pd.DataFrame:

    recs = db_books.similarity_search(query, k=50)


    books_list = [
        int(doc.page_content.strip().replace('"','').split()[0])
        for doc in recs
    ]

    # Return the top_k matching books from dataframe
    return books[books["isbn13"].isin(books_list)].head(top_k)

In [30]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_description,title_and_subtitle,tagged_description
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,0,The Family Way,9780007151240 It should be the most natural th...
143,9780060546571,0060546573,Three Rotten Eggs,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=t2pWl...,The students of Miss Earth's class in rural Ve...,2005.0,3.74,240.0,76.0,0,Three Rotten Eggs,9780060546571 The students of Miss Earth's cla...
146,9780060556501,0060556501,"The Lion, the Witch and the Wardrobe (picture ...",C. S. Lewis,Juvenile Fiction,http://books.google.com/books/content?id=FlSpp...,Narnia: A magical land full of wonder and exci...,2004.0,4.19,48.0,5012.0,0,"The Lion, the Witch and the Wardrobe (picture ...",9780060556501 Narnia: A magical land full of w...
256,9780060845247,0060845244,"The Lion, the Witch and the Wardrobe Read-Alou...",C. S. Lewis;Pauline Baynes,Juvenile Fiction,http://books.google.com/books/content?id=deiyG...,Four English school children enter the magic l...,2005.0,4.21,189.0,56.0,0,"The Lion, the Witch and the Wardrobe Read-Alou...",9780060845247 Four English school children ent...
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,0,Prodigal Summer: A Novel,9780060959036 Barbara Kingsolver's fifth novel...
373,9780061131622,0061131628,Mandy,Julie Andrews Edwards,Juvenile Fiction,http://books.google.com/books/content?id=5dNj_...,"Mandy, a ten-year-old orphan, dreams of a plac...",2006.0,4.24,320.0,9482.0,0,Mandy,"9780061131622 Mandy, a ten-year-old orphan, dr..."
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."
427,9780064434874,0064434877,Christmas in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=FT1Yp...,"Long ago, a little girl named Laura Ingalls li...",1997.0,4.19,32.0,2062.0,0,Christmas in the Big Woods,"9780064434874 Long ago, a little girl named La..."
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
430,9780064435260,0064435261,A Little Prairie House,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=pRSju...,"Long, long ago, a little girl named Laura Inga...",1999.0,4.19,32.0,1533.0,0,A Little Prairie House,"9780064435260 Long, long ago, a little girl na..."
431,9780064440578,0064440575,Grizzwold,Syd Hoff,Juvenile Fiction,http://books.google.com/books/content?id=Sy_X4...,Grizzwold the lovable bear is having a tough t...,1984.0,3.80,64.0,206.0,0,Grizzwold,9780064440578 Grizzwold the lovable bear is ha...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,0,The Sense of Wonder,9780067575208 First published more than three ...
645,9780140364750,0140364757,Seventeen & In-Between,Barthe DeClements,High schools,http://books.google.com/books/content?id=ptENP...,"At seventeen, Elsie Edwards, once the fat girl...",1993.0,3.82,176.0,221.0,0,Seventeen & In-Between: A Novel,"9780140364750 At seventeen, Elsie Edwards, onc..."
692,9780140448009,0140448004,Three Tales,Gustave Flaubert;Roger Whitehouse;Geoffrey Wall,Fiction,http://books.google.com/books/content?id=XFzga...,Features short fiction by the French naturalis...,2005.0,3.71,110.0,3050.0,0,Three Tales,9780140448009 Features short fiction by the Fr...
763,9780141186078,0141186070,The Log from the Sea of Cortez,John Steinbeck,Biography & Autobiography,http://books.google.com/books/content?id=9CrIf...,This light-hearted journal tells of John Stein...,2001.0,3.84,288.0,3226.0,0,The Log from the Sea of Cortez,9780141186078 This light-hearted journal tells...
817,9780142403013,0142403016,Moon-Flash,Patricia A. McKillip,Juvenile Fiction,http://books.google.com/books/content?id=wS-Xh...,After dreaming that they must leave their isol...,2005.0,3.73,304.0,340.0,0,Moon-Flash,9780142403013 After dreaming that they must le...
1247,9780312369347,0312369344,Beatrix Potter,Linda Lear,Biography & Autobiography,http://books.google.com/books/content?id=T9uTx...,"Peter Rabbit, Mr. McGregor, and many other Bea...",2007.0,4.03,584.0,1270.0,0,Beatrix Potter: A Life in Nature,"9780312369347 Peter Rabbit, Mr. McGregor, and ..."
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
1642,9780374522599,0374522596,The Control of Nature,John McPhee,Nature,http://books.google.com/books/content?id=p1qKQ...,The Control of Nature is John McPhee's bestsel...,1990.0,4.24,288.0,3365.0,0,The Control of Nature,9780374522599 The Control of Nature is John Mc...
1880,9780385732550,0385732554,The Giver,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=oZRlY...,"At the age of twelve, Jonas, a young boy from ...",2006.0,4.12,208.0,1464909.0,0,The Giver,"9780385732550 At the age of twelve, Jonas, a y..."
1907,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in...,William Cronon,Law,http://books.google.com/books/content?id=w04mj...,"Essays by revisionist historians, scientists, ...",1996.0,4.16,560.0,649.0,0,Uncommon Ground: Rethinking the Human Place in...,9780393315110 Essays by revisionist historians...
1943,9780393959055,0393959058,"Walden ; And, Resistance to Civil Government",Henry David Thoreau,Literary Collections,http://books.google.com/books/content?id=uVxnQ...,The classic chronicle of a communion with natu...,1992.0,3.95,482.0,232.0,0,"Walden ; And, Resistance to Civil Government: ...",9780393959055 The classic chronicle of a commu...
2126,9780439569729,0439569729,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),Terry Cooper,Education,http://books.google.com/books/content?id=b-EBH...,"416 bright, colorful pages that give kids prac...",2003.0,4.57,416.0,7.0,0,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),"9780439569729 416 bright, colorful pages that ..."
2155,9780439872478,0439872472,Violet Makes a Splash,Anne Mazer,Juvenile Fiction,http://books.google.com/books/content?id=ldJMV...,When Violet conjures a pool for their yard and...,2007.0,3.95,112.0,116.0,0,Violet Makes a Splash,9780439872478 When Violet conjures a pool for ...
2163,9780439994125,0439994128,Northern Lights,Philip Pullman,Arctic regions,http://books.google.com/books/content?id=GFcYA...,Twelve year-old Lyra Belacqua is drawn into a ...,2001.0,3.96,399.0,751.0,0,Northern Lights,9780439994125 Twelve year-old Lyra Belacqua is...
2203,9780440410256,0440410258,Escape from Fire Mountain,Gary Paulsen,Juvenile Fiction,http://books.google.com/books/content?id=jvhtD...,Thirteen-year-old Nikki Roberts tries to help ...,1995.0,3.70,80.0,112.0,0,Escape from Fire Mountain,9780440410256 Thirteen-year-old Nikki Roberts ...
2219,9780440910817,0440910811,A Ring of Endless Light,Madeleine L'Engle,Death,http://books.google.com/books/content?id=UGoVw...,During the summer her grandfather is dying of ...,1995.0,4.15,332.0,16513.0,0,A Ring of Endless Light,9780440910817 During the summer her grandfathe...
2410,9780451457592,0451457595,The River's Gift,Mercedes Lackey,Fiction,http://books.google.com/books/content?id=qLonv...,Fifteen-year-old Ariella spends her days in th...,1999.0,3.88,128.0,1029.0,0,The River's Gift,9780451457592 Fifteen-year-old Ariella spends ...
2668,9780553213973,0553213970,Journey To The Center Of The Earth,Jules Verne,Fiction,http://books.google.com/books/content?id=4_dvD...,"Follows Professor Hardwigg, his nephew Harry, ...",2006.0,3.85,240.0,101764.0,0,Journey To The Center Of The Earth,"9780553213973 Follows Professor Hardwigg, his ..."
2805,9780571084838,0571084834,Lord of the Flies,William Golding,Airplane crash survival,NaN,After a plane crash strands them on a tropical...,1954.0,3.67,223.0,4498.0,0,Lord of the Flies,9780571084838 After a plane crash strands them...
3201,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,0,A Child's Garden of Verses,9780689823824 Here is a delightful look at chi...
3213,9780689860072,0689860072,Dragonsinger,Anne McCaffrey,Juvenile Fiction,http://books.google.com/books/content?id=IiLlZ...,"Menolly flees her home, because she is not per...",2003.0,4.28,288.0,34207.0,0,Dragonsinger,"9780689860072 Menolly flees her home, because ..."
3215,9780689862465,0689862466,The Octopus,Cynthia Rylant;Preston McDaniels,Juvenile Fiction,http://books.google.com/books/content?id=8B8-C...,"Whistler and Lila, two of the mice children wh...",2005.0,4.16,64.0,117.0,0,The Octopus,"9780689862465 Whistler and Lila, two of the mi..."
3470,9780747566755,0747566755,The Story of Mr Sommer,Patrick Süskind;Michael Hofmann,Fiction,http://books.google.com/books/content?id=jD4hH...,A boy's village childhood with all the traditi...,2003.0,3.85,128.0,1974.0,0,The Story of Mr Sommer,9780747566755 A boy's village childhood with a...
3580,9780763619312,0763619310,Judy Moody Gets Famous!,Megan McDonald;Peter Reynolds,Juvenile Fiction,http://books.google.com/books/content?id=11tdd...,When a third grade classmate gets her picture ...,2003.0,4.03,144.0,8080.0,0,Judy Moody Gets Famous!,9780763619312 When a third grade classmate get...
3586,9780763628109,0763628107,The Dragon's Eye,Dugald Steer,Juvenile Fiction,http://books.google.com/books/content?id=kasIo...,When twelve-year-old Daniel Cook and his siste...,2006.0,3.82,221.0,2139.0,0,The Dragon's Eye,9780763628109 When twelve-year-old Daniel Cook...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
3764,9780786818723,0786818727,Baby Einstein: Violet's House,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=bC4HA...,"Violet, a very curious young mouse, invites ba...",2003.0,3.98,10.0,39.0,0,Baby Einstein: Violet's House: A Giant Touch-a...,"9780786818723 Violet, a very curious young mou..."
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,0,"Baby Einstein: Water, Water Everywhere",9780786819119 Charming illustrations and playf...
3767,9780786849734,0786849738,Disney's Little Einsteins: Galactic Goodnight,Susan Ring,Juvenile Fiction,http://books.google.com/books/content?id=Nm3N3...,"The Little Einsteins, equipped with their came...",2006.0,4.50,20.0,10.0,0,Disney's Little Einsteins: Galactic Goodnight,"9780786849734 The Little Einsteins, equipped w..."
4241,9780915811236,0915811235,Secret of the Peaceful Warrior,Dan Millman,Juvenile Fiction,http://books.google.com/books/content?id=QulFq...,An old man named Socrates shows Danny that the...,1991.0,4.18,32.0,152.0,0,Secret of the Peaceful Warrior,9780915811236 An old man named Socrates shows ...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...
4331,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,218.0,0,Providence of a Sparrow: Lessons from a Life G...,9781400033850 Describes the influence of a fou...
4596,9781560067849,1560067845,Flowers for Algernon,Patrice Cassedy,Juvenile Nonfiction,http://books.google.com/books/content?id=x_CUf...,"Discusses the young adult book ""Flowers for Al...",2000.0,3.00,96.0,1.0,0,Flowers for Algernon,"9781560067849 Discusses the young adult book ""..."
4602,9781560258506,1560258500,Monster Island,David Wellington,Fiction,http://books.google.com/books/content?id=Bpsmi...,It's one month after a global disaster. Manhat...,2006.0,3.60,282.0,9635.0,0,Monster Island: A Zombie Novel,9781560258506 It's one month after a global di...
4830,9781590171035,1590171039,Mistress Masham's Repose,T. H. White;Fritz Eichenberg,Juvenile Fiction,http://books.google.com/books/content?id=J_Sg2...,"Ten-year-old Maria, an orphaned heiress living...",1946.0,3.94,260.0,1404.0,0,Mistress Masham's Repose,"9781590171035 Ten-year-old Maria, an orphaned ..."